#!/usr/bin/env python3
f = [x for x in open("trivia", "r").read().split("\n") if x != ""]
l = []
l.append("#pragma once")
l.append("")
l.append("// This file was autogenerated by trivia.py")
l.append("")
l.append("#define N_TRIVIA " + str(len(f)))
l.append("")
l.append("#ifdef DEFINE_TRIVIA")
l.append("")
l.append("#include <WString.h>")
l.append("")
l.append("const __FlashStringHelper* trivia(int n) {")
l.append("    switch (n) {")
for i in range(len(f)):
	w = f[i]
	l.append("        case "+str(i)+": return F(\"" + w.replace('"', '\\"') + "\");")
l.append("    }")
l.append("}")
l.append("")
l.append("#endif")

open("trivia.h", "w").write("\n".join(l))
