#pragma once

typedef enum franchize_t {
	SMASH = 0,
	MARIO = 1,
	DK = 2,
	ZELDA = 3,
	KIRBY = 4,
	METROID = 5,
	YOSHI = 6,
	STARFOX = 7,
	POKEMON = 8,
	EARTHBOUND = 9,
	FZERO = 10,
	ICIES = 11,
	FE = 12,
	GAMENWATCH = 13,
	ICARUS = 14,
	WARIO = 15,
	METAL_GEAR = 16,
	SONIC = 17,
	PIKMIN = 18, // needs help
	ROB = 19,
	AC = 20,
	MEGA_MAN = 21, // needs help
	WIIFIT = 22,
	PUNCH_OUT = 23,
	PACMAN = 24,
	DUCK_HUNT = 25,
	STREET_FIGHTER = 26,
	FF = 27,
	BAYONETTA = 28,
	SPLATOON = 29,
	CASTLEVANIA = 30, // needs help
	PERSONA = 31,
	DQ = 32,
	BANJO_KAZOOIE = 33, // needs help
	ARMS = 34, // needs LOTS OF help
	MC = 35,
	XENOBLADE = 36, // needs help
	FATAL_FURY = 37,
} franchize_t;

const int N_FRANCHIZE = 38;

typedef struct smasher_t {
	const char* name;
	franchize_t franchize;
} smasher_t;

const int N_SMASHERS = 82;
const smasher_t smashers[N_SMASHERS] = {
	{"Mario", MARIO},
	{"Donkey Kong", DK},
	{"Link", ZELDA},
	{"Samus", METROID},
	{"Dark Samus", METROID},
	{"Yoshi", YOSHI},
	{"Kirby", KIRBY},
	{"Fox", STARFOX},
	{"Pikachu", POKEMON},
	{"Luigi", MARIO},
	{"Ness", EARTHBOUND},
	{"Captain Falcon", FZERO},
	{"Jigglypuff", POKEMON},
	{"Peach", MARIO},
	{"Daisy", MARIO},
	{"Bowser", MARIO},
	{"Ice Climbers", ICIES},
	{"Sheik", ZELDA},
	{"Zelda", ZELDA},
	{"Dr. Mario", MARIO},
	{"Pichu", POKEMON},
	{"Falco", STARFOX},
	{"Marth", FE},
	{"Lucina", FE},
	{"Young Link", ZELDA},
	{"Ganondorf", ZELDA},
	{"Mewtwo", POKEMON},
	{"Roy", FE},
	{"Chrom", FE},
	{"Mr.Game&Watch", GAMENWATCH},
	{"Meta Knight", KIRBY},
	{"Pit", ICARUS},
	{"Dark Pit", ICARUS},
	{"Zero Suit Samus", METROID},
	{"Wario", WARIO},
	{"Snake", METAL_GEAR},
	{"Ike", FE},
	{"Pokemon Trainer", POKEMON},
	{"Diddy Kong", DK},
	{"Lucas", EARTHBOUND},
	{"Sonic", SONIC},
	{"King Dedede", KIRBY},
	{"Olimar", PIKMIN},
	{"Lucario", POKEMON},
	{"R.O.B.", ROB},
	{"Toon Link", ZELDA},
	{"Wolf", STARFOX},
	{"Villager", AC},
	{"Mega Man", MEGA_MAN},
	{"Wii Fit Trainer", WIIFIT},
	{"Rosalina&Luma", MARIO},
	{"Little Mac", PUNCH_OUT},
	{"Greninja", POKEMON},
	{"Mii Fighter", SMASH},
	{"Palutena", ICARUS},
	{"PAC-MAN", PACMAN},
	{"Robin", FE},
	{"Shulk", XENOBLADE},
	{"Bowser Jr", MARIO},
	{"Duck Hunt", DUCK_HUNT},
	{"Ryu", STREET_FIGHTER},
	{"Ken", STREET_FIGHTER},
	{"Cloud", FF},
	{"Corrin", FE},
	{"Bayonetta", BAYONETTA},
	{"Inkling", SPLATOON},
	{"Ridley", METROID},
	{"Simon", CASTLEVANIA},
	{"Richter", CASTLEVANIA},
	{"King K. Rool", DK},
	{"Isabelle", AC},
	{"Incineroar", POKEMON},
	{"Piranha Plant", MARIO},
	{"Joker", PERSONA},
	{"Hero", DQ},
	{"Banjo&Kazooie", BANJO_KAZOOIE},
	{"Terry", FATAL_FURY},
	{"Byleth", FE},
	{"Min Min", ARMS},
	{"Steve/Alex", MC},
	{"Sephiroth", FF},
	{"Pyra/Mythra", XENOBLADE}
};
